// flow-typed signature: 5b2930caf1cc5912063d5438488754ac
// flow-typed version: <<STUB>>/babel-plugin-syntax-object-rest-spread_v^6.13.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-syntax-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-syntax-object-rest-spread' {
  declare module.exports: any;
}
