// flow-typed signature: e9855afe933bc7ddacc10959b57e2ac9
// flow-typed version: <<STUB>>/colors_v1.1.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'colors' {
  declare module.exports: any;
}
