// flow-typed signature: 3f5fa643b15a720c243ee448fdcc21ac
// flow-typed version: <<STUB>>/cross-env_v5.1.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}
