// flow-typed signature: 941d80e170af0bf6e65a69ac51b027b1
// flow-typed version: <<STUB>>/fastest-validator_v^0.6.12/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastest-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fastest-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fastest-validator/dist/browser/index' {
  declare module.exports: any;
}

declare module 'fastest-validator/dist/browser/index.min' {
  declare module.exports: any;
}

declare module 'fastest-validator/dist/index' {
  declare module.exports: any;
}

declare module 'fastest-validator/dist/index.min' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/browser-with-rollup/rollup.config' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/browser-with-rollup/src/index' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/custom' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/full' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/index' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/multi' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/precompiled' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/start' {
  declare module.exports: any;
}

declare module 'fastest-validator/examples/with-react-nextjs/pages/index' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/helpers/deep-extend' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/helpers/flatten' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/messages' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/any' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/array' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/boolean' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/custom' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/date' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/email' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/enum' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/forbidden' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/function' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/number' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/object' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/string' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/rules/url' {
  declare module.exports: any;
}

declare module 'fastest-validator/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fastest-validator/dist/browser/index.js' {
  declare module.exports: $Exports<'fastest-validator/dist/browser/index'>;
}
declare module 'fastest-validator/dist/browser/index.min.js' {
  declare module.exports: $Exports<'fastest-validator/dist/browser/index.min'>;
}
declare module 'fastest-validator/dist/index.js' {
  declare module.exports: $Exports<'fastest-validator/dist/index'>;
}
declare module 'fastest-validator/dist/index.min.js' {
  declare module.exports: $Exports<'fastest-validator/dist/index.min'>;
}
declare module 'fastest-validator/examples/browser-with-rollup/rollup.config.js' {
  declare module.exports: $Exports<'fastest-validator/examples/browser-with-rollup/rollup.config'>;
}
declare module 'fastest-validator/examples/browser-with-rollup/src/index.js' {
  declare module.exports: $Exports<'fastest-validator/examples/browser-with-rollup/src/index'>;
}
declare module 'fastest-validator/examples/custom.js' {
  declare module.exports: $Exports<'fastest-validator/examples/custom'>;
}
declare module 'fastest-validator/examples/full.js' {
  declare module.exports: $Exports<'fastest-validator/examples/full'>;
}
declare module 'fastest-validator/examples/index.js' {
  declare module.exports: $Exports<'fastest-validator/examples/index'>;
}
declare module 'fastest-validator/examples/multi.js' {
  declare module.exports: $Exports<'fastest-validator/examples/multi'>;
}
declare module 'fastest-validator/examples/precompiled.js' {
  declare module.exports: $Exports<'fastest-validator/examples/precompiled'>;
}
declare module 'fastest-validator/examples/start.js' {
  declare module.exports: $Exports<'fastest-validator/examples/start'>;
}
declare module 'fastest-validator/examples/with-react-nextjs/pages/index.js' {
  declare module.exports: $Exports<'fastest-validator/examples/with-react-nextjs/pages/index'>;
}
declare module 'fastest-validator/index' {
  declare module.exports: $Exports<'fastest-validator'>;
}
declare module 'fastest-validator/index.js' {
  declare module.exports: $Exports<'fastest-validator'>;
}
declare module 'fastest-validator/lib/helpers/deep-extend.js' {
  declare module.exports: $Exports<'fastest-validator/lib/helpers/deep-extend'>;
}
declare module 'fastest-validator/lib/helpers/flatten.js' {
  declare module.exports: $Exports<'fastest-validator/lib/helpers/flatten'>;
}
declare module 'fastest-validator/lib/messages.js' {
  declare module.exports: $Exports<'fastest-validator/lib/messages'>;
}
declare module 'fastest-validator/lib/rules/any.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/any'>;
}
declare module 'fastest-validator/lib/rules/array.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/array'>;
}
declare module 'fastest-validator/lib/rules/boolean.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/boolean'>;
}
declare module 'fastest-validator/lib/rules/custom.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/custom'>;
}
declare module 'fastest-validator/lib/rules/date.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/date'>;
}
declare module 'fastest-validator/lib/rules/email.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/email'>;
}
declare module 'fastest-validator/lib/rules/enum.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/enum'>;
}
declare module 'fastest-validator/lib/rules/forbidden.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/forbidden'>;
}
declare module 'fastest-validator/lib/rules/function.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/function'>;
}
declare module 'fastest-validator/lib/rules/number.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/number'>;
}
declare module 'fastest-validator/lib/rules/object.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/object'>;
}
declare module 'fastest-validator/lib/rules/string.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/string'>;
}
declare module 'fastest-validator/lib/rules/url.js' {
  declare module.exports: $Exports<'fastest-validator/lib/rules/url'>;
}
declare module 'fastest-validator/lib/validator.js' {
  declare module.exports: $Exports<'fastest-validator/lib/validator'>;
}
