// flow-typed signature: 995f15658893f47a68aece9ea7e81f22
// flow-typed version: <<STUB>>/rollup-plugin-node-resolve_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-node-resolve' {
  declare module.exports: any;
}
