// flow-typed signature: 65b468f3ca48c05dd9f75c482f053194
// flow-typed version: <<STUB>>/rx-socket_v^0.5.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rx-socket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rx-socket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rx-socket/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rx-socket/lib/index.js' {
  declare module.exports: $Exports<'rx-socket/lib/index'>;
}
