// flow-typed signature: e1171bad33a469e6da7305891160e157
// flow-typed version: <<STUB>>/sinon_v4.3.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sinon' {
  declare module.exports: any;
}
