// flow-typed signature: 49fbc559c63ab1774e407dec842c4c6a
// flow-typed version: <<STUB>>/sodium-universal_v^2.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sodium-universal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sodium-universal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sodium-universal/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sodium-universal/browser.js' {
  declare module.exports: $Exports<'sodium-universal/browser'>;
}
declare module 'sodium-universal/index' {
  declare module.exports: $Exports<'sodium-universal'>;
}
declare module 'sodium-universal/index.js' {
  declare module.exports: $Exports<'sodium-universal'>;
}
