// flow-typed signature: e2c1eaa933b4a1130070e4155b9b40d7
// flow-typed version: <<STUB>>/typings_v^2.0.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typings' {
  declare module.exports: any;
}
