// flow-typed signature: d1de7d39929f9f2089f9725ac3111e03
// flow-typed version: <<STUB>>/webpack_v1.13.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}
