// flow-typed signature: 2487d05befc5d4c73f8ef97c4337e30d
// flow-typed version: <<STUB>>/rollup_v0.36.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}
